import { container } from "tsyringe";
import { ISender } from "./domain/interfaces/ISender";
import { Sender } from "./utils/sender";
import IUserRepository from "./domain/interfaces/IUserRepository";
import MongoUserRepository from "./repository/mongoUserRepository";
import IEstablishmentRepository from "./domain/interfaces/IEstablishmentRepository";
import MongoEstablishmentRespository from "./repository/mongoEstablishmentRepository";
import IOrderRepository from "./domain/interfaces/IOrderRepository";
import MongoOrderRepository from "./repository/mongoOrderRepository";
import IAccountRepository from "./domain/interfaces/IAccountRepository";
import MongoAccountRepository from "./repository/mongoAccountRepository";
import ISpoolHandler from "./domain/interfaces/ISpoolHandler";
import SpoolHandler from "./domain/handlers/spoolHandler";
import IPrinterRepository from "./domain/interfaces/IPrinterRepository";
import MongoPrinterRepository from "./repository/mongoPrinterRepository";
import ICloudService from "./domain/interfaces/ICloudService";
import CloudService from "./utils/cloud/cloudService";
import { IAddonesRepository } from "./domain/interfaces/IAddonesRepository";
import { MongoAddonesRepository } from "./repository/mongoAddoneRepository";
import ICategoryRepository from "./domain/interfaces/ICategoryRepository";
import MongoCategoryRepository from "./repository/mongoCategoryRepository";
import { IProductRepository } from "./domain/interfaces/IProductRepository";
import { MongoProductRepository } from "./repository/mongoProductRepository";
import IAppRepository from "./domain/interfaces/IAppRepository";
import { MongoAppRepository } from "./repository/mongoAppRepository";
import { IUtilities } from "./domain/interfaces/IUtilities";
import { Utilities } from "./utils/utilities";
import { IProductHandler } from "./domain/interfaces/IProductHandler";
import ProductHandler from "./domain/handlers/products/productCreationHandler";

container.register<ISender>("ISender", Sender);
container.register<IUserRepository>("IUserRepository", MongoUserRepository);
container.register<IEstablishmentRepository>("IEstablishmentRepository", MongoEstablishmentRespository);
container.register<IOrderRepository>("IOrderRepository", MongoOrderRepository);
container.register<IAccountRepository>("IAccountRepository", MongoAccountRepository);
container.register<ISpoolHandler>("ISpoolHandler", SpoolHandler);
container.register<IPrinterRepository>("IPrinterRepository", MongoPrinterRepository);
container.register<ICloudService>("ICloudService", CloudService);
container.register<IAddonesRepository>("IAddonesRepository", MongoAddonesRepository);
container.register<ICategoryRepository>("ICategoryRepository", MongoCategoryRepository);
container.register<IProductRepository>("IProductRepository", MongoProductRepository);
container.register<IAppRepository>("IAppRepository", MongoAppRepository);
container.register<IUtilities>("IUtilities", Utilities);
container.register<IProductHandler>("IProductHandler", ProductHandler);