name: Deploy to Google App Engine (Test)

on:
    push:
        branches:
            - payment_methods

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Set up Cloud SDK
            uses: google-github-actions/setup-gcloud@v0.2.0
            with:
              version: 'latest'
              service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
              project_id: ${{ secrets.GCP_PROJECT_ID }}

          - name: Deploy to App Engine (Test)
            run: |
              gcloud app deploy --quiet --no-promote --version=${{secrets.APP_ENGINE_VERSION}}