name: Deploy to Google App Engine PROD

on:
    pull_request: 
      branches: 
        ["main"]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: "Create firebase.json file"
            env: 
              FIREBASE_JSON: ${{secrets.FIREBASE_JSON}}
            run: |
              echo "$FIREBASE_JSON" > firebase_config.json

          - name: "Create Prod Certificate"
            env:
              CERTIFICATE_P12: ${{secrets.PROD_CERTIFICATE}}
            run: |
              echo "$CERTIFICATE_P12" | base64 -d > config/producao.p12

          - name: Create app.yaml
            env:
              APP_YAML_FILE: ${{secrets.APP_YAML_FILE}}
            run: |
              echo "$APP_YAML_FILE" > app.yaml

          - name: Set up Cloud SDK
            uses: google-github-actions/setup-gcloud@v0.2.0
            with:
              version: 'latest'
              service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
              project_id: ${{ secrets.GCP_PROJECT_ID }}


          - name: Deploy to App Engine
            run: |
              gcloud app deploy app.yaml --quiet