name: "Limpeza de pedidos antigos"
on:
  schedule:
    - cron: '0 0 */1 * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  delete-endpoint:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Limpeza de pedidos antigos a mais de 5 dias.
        run: |
          curl -X DELETE ${{secrets.CLEAN_OLD_ORDERS}}
